-- FHS Supabase Initial Schema
-- Migration: 0001_initial_schema
-- Created: 2026-05-10
-- Phase 1 of Supabase dual-system setup
--
-- AGENTS.md Hard Rules enforced:
--   [1] raw_form_state JSONB NOT NULL — never remove (order restore lifeline)
--   [2] final_sale_price NOT NULL DEFAULT 0 — frontend truth, no trigger allowed
--   [3] net_profit / *_cost written by n8n — no generated columns
--   [4] sku UNIQUE on products — n8n exact string match dependency
--   [5] No trigger that recalculates financial fields
--
-- database-reviewer fixes applied (2026-05-10):
--   P0: order_items uses order_fhs_id VARCHAR(20) FK (n8n writes by FHS-XXXXX, not UUID)
--   P0: final_sale_price NOT NULL DEFAULT 0
--   P1: process_status uses ENUM type
--   P1: added idx_orders_customer_name (text_pattern_ops)
--   P2: products.cost_config_id ON DELETE SET NULL
--   P2: sales_pipeline has pipeline_key for upsert
--   P3: batch_number on order_items is intentional denormalization (documented)

-- ============================================================
-- ENUMS
-- ============================================================

CREATE TYPE order_status AS ENUM (
  '待確認', '製作中', '完成', '已取件', '已取消'
);

CREATE TYPE item_status AS ENUM (
  '待製作', '製作中', '完成', '已取件'
);

CREATE TYPE pipeline_stage AS ENUM (
  '新查詢', '跟進中', '已報價', '已成交', '已取消'
);

CREATE TYPE ai_status_type AS ENUM (
  '待處理', '已處理', '忽略'
);

-- ============================================================
-- TABLE: cost_configurations  (Base_Costs)
-- Must be created before products (FK dependency)
-- ============================================================

CREATE TABLE cost_configurations (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  config_name VARCHAR(100) UNIQUE NOT NULL,
  drawing_cost   NUMERIC(10,2) DEFAULT 0,
  printing_cost  NUMERIC(10,2) DEFAULT 0,
  clasp_cost     NUMERIC(10,2) DEFAULT 0,
  shipping_cost  NUMERIC(10,2) DEFAULT 0,
  updated_at  TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE cost_configurations IS
  'Maps to Airtable Base_Costs. Low-frequency updates (vendor price changes only). '
  'n8n reads this for cost calculation. Human updates via Airtable, sync to Supabase via script.';

-- ============================================================
-- TABLE: products  (Product_Database)
-- ============================================================

CREATE TABLE products (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sku            VARCHAR(200) UNIQUE NOT NULL,
  -- CRITICAL: sku must match n8n Parse Items & Generate SKU node output exactly
  main_category  VARCHAR(100),
  target_object  VARCHAR(100),
  material       VARCHAR(100),
  mode           VARCHAR(50),
  item_per_set   INTEGER DEFAULT 1,
  total_base_cost NUMERIC(10,2),
  -- total_base_cost written by n8n; do NOT use generated column
  cost_config_id UUID REFERENCES cost_configurations(id) ON DELETE SET NULL,
  suggested_price NUMERIC(10,2),
  markup_factor   NUMERIC(5,2) DEFAULT 2.5,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_products_sku           ON products(sku);
CREATE INDEX idx_products_main_category ON products(main_category);

COMMENT ON TABLE products IS
  'Maps to Airtable Product_Database. 104 SKUs. '
  'sku field is the n8n exact-match key — do NOT rename or reformat values.';

COMMENT ON COLUMN products.total_base_cost IS
  'Written by n8n after cost calculation. AGENTS.md: no generated column allowed.';

-- ============================================================
-- TABLE: orders  (Main_Orders)
-- ============================================================

CREATE TABLE orders (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id           VARCHAR(20) UNIQUE NOT NULL,
  -- order_id format: FHS-XXXXX (generated by Dashboard)
  -- n8n and other tables reference orders via order_id (VARCHAR), not UUID
  confirmed_at       DATE,
  customer_name      TEXT,
  appointment_at     DATE,
  deposit            NUMERIC(10,2) DEFAULT 0,
  balance            NUMERIC(10,2) DEFAULT 0,
  additional_fee     NUMERIC(10,2) DEFAULT 0,
  adjustment_amount  NUMERIC(10,2) DEFAULT 0,

  -- FINANCIAL TRUTH FIELDS — written by Dashboard/n8n, no trigger recalculation
  final_sale_price   NUMERIC(10,2) NOT NULL DEFAULT 0,
  -- NOT NULL: AGENTS.md financial truth guard. DEFAULT 0 triggers Profit Auditor alert path.
  total_cost         NUMERIC(10,2),
  handmodel_cost     NUMERIC(10,2),
  keychain_cost      NUMERIC(10,2),
  necklace_cost      NUMERIC(10,2),
  net_profit         NUMERIC(10,2),
  -- net_profit = final_sale_price - total_cost, calculated by n8n, written here

  full_order_text    TEXT,
  batch_number       VARCHAR(50),
  admin_notes        TEXT,
  process_status     order_status DEFAULT '待確認',
  raw_form_state     JSONB NOT NULL DEFAULT '{}',
  -- AGENTS.md: Raw_Form_State 不可侵犯. This is the order restore lifeline.
  -- Written by Dashboard only. n8n and Supabase read-only.

  created_at         TIMESTAMPTZ DEFAULT NOW(),
  updated_at         TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_orders_order_id        ON orders(order_id);
CREATE INDEX idx_orders_confirmed_at    ON orders(confirmed_at);
CREATE INDEX idx_orders_process_status  ON orders(process_status);
CREATE INDEX idx_orders_customer_name   ON orders(customer_name text_pattern_ops);
-- text_pattern_ops supports LIKE 'prefix%' for Dashboard autocomplete search

COMMENT ON TABLE orders IS
  'Maps to Airtable Main_Orders. Core order table. '
  'raw_form_state must never be removed — it is the sole mechanism for order restoration.';

COMMENT ON COLUMN orders.final_sale_price IS
  'AGENTS.md: Frontend Truth. Written by Dashboard. '
  'n8n must NEVER recalculate this value. No trigger allowed.';

COMMENT ON COLUMN orders.raw_form_state IS
  'AGENTS.md: 不可侵犯. Serialized by captureFormState() in Dashboard. '
  'Do not modify schema or remove this column.';

-- Trigger to auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- TABLE: order_items  (Order_Items)
-- ============================================================

CREATE TABLE order_items (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  item_key       VARCHAR(100) UNIQUE NOT NULL,
  -- item_key format: [order_id]_[category]_[limb] e.g. FHS-00123_K_LH
  -- Upsert key used by n8n Create Sub Items node

  -- FK uses order_fhs_id (VARCHAR) not UUID.
  -- Reason: n8n writes order_id as FHS-XXXXX string, not the internal UUID.
  -- Doing a UUID lookup before every insert would add latency and complexity.
  order_fhs_id   VARCHAR(20) NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,

  -- product reference by sku (human-readable, matches n8n output)
  product_sku    VARCHAR(200) REFERENCES products(sku) ON UPDATE CASCADE,

  item_category  TEXT,
  quantity       INTEGER NOT NULL DEFAULT 1,

  -- Cost fields: written by n8n after SKU normalization and cost lookup
  item_base_cost NUMERIC(10,2),
  subtotal_cost  NUMERIC(10,2),
  handmodel_cost NUMERIC(10,2),
  keychain_cost  NUMERIC(10,2),
  necklace_cost  NUMERIC(10,2),

  engraving_text    TEXT,
  specification     TEXT,
  process_status    item_status DEFAULT '待製作',
  reference_image_url TEXT[],
  ai_suggestion     TEXT,

  -- Intentional denormalization: batch_number duplicated from parent order.
  -- Reason: n8n writes it here for direct item-level queries without JOIN.
  -- Risk: drift if order batch_number changes after items written.
  -- Mitigation: sync_audit_quadruple.js checks for drift.
  batch_number   VARCHAR(50),

  created_at     TIMESTAMPTZ DEFAULT NOW(),
  updated_at     TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_order_items_order_fhs_id ON order_items(order_fhs_id);
CREATE INDEX idx_order_items_item_key     ON order_items(item_key);
CREATE INDEX idx_order_items_product_sku  ON order_items(product_sku);

CREATE TRIGGER order_items_updated_at
  BEFORE UPDATE ON order_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

COMMENT ON TABLE order_items IS
  'Maps to Airtable Order_Items. Child records of orders. '
  'item_key is the n8n upsert key. order_fhs_id is VARCHAR FK to avoid UUID lookup overhead in n8n.';

COMMENT ON COLUMN order_items.order_fhs_id IS
  'VARCHAR FK to orders.order_id (FHS-XXXXX). '
  'n8n writes this directly without needing to resolve UUID first.';

-- ============================================================
-- TABLE: sales_pipeline  (Sales_Pipeline)
-- ============================================================

CREATE TABLE sales_pipeline (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pipeline_key     VARCHAR(200) UNIQUE,
  -- pipeline_key: dedup anchor. Format: customer_name + '_' + date(YYYY-MM-DD)
  -- n8n should set this before upsert to prevent duplicates on retry.

  customer_name    TEXT,
  stage            pipeline_stage DEFAULT '新查詢',
  order_type       VARCHAR(50),
  source           VARCHAR(50),
  query_details    TEXT,
  estimated_amount NUMERIC(10,2),
  ai_next_step     TEXT,
  raw_message      TEXT,
  ai_status        ai_status_type DEFAULT '待處理',
  created_at       TIMESTAMPTZ DEFAULT NOW(),
  updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_pipeline_stage      ON sales_pipeline(stage);
CREATE INDEX idx_pipeline_ai_status  ON sales_pipeline(ai_status);

CREATE TRIGGER sales_pipeline_updated_at
  BEFORE UPDATE ON sales_pipeline
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- TABLE: error_logs  (Error_Logs)
-- ============================================================

CREATE TABLE error_logs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  occurred_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  workflow_name TEXT,
  error_message TEXT,
  node_name     TEXT
);

CREATE INDEX idx_error_logs_occurred_at ON error_logs(occurred_at DESC);

COMMENT ON TABLE error_logs IS
  'Append-only. n8n Error Trigger writes here. '
  'TTL: 30 days. Cleanup via pg_cron (see ANTI_IDLE_SETUP.md). '
  'WARNING: pg_cron pauses when Supabase Free Tier project is inactive for 7 days.';

-- ============================================================
-- pg_cron: Error_Logs 30-day TTL cleanup
-- Run this manually in Supabase SQL Editor after enabling pg_cron:
-- ============================================================
-- SELECT cron.schedule(
--   'delete-old-error-logs',
--   '0 3 * * *',
--   $$DELETE FROM error_logs WHERE occurred_at < NOW() - INTERVAL '30 days'$$
-- );
-- ============================================================

-- ============================================================
-- SAFETY: No financial triggers
-- The following trigger types are EXPLICITLY FORBIDDEN per AGENTS.md:
--   - Any trigger that modifies final_sale_price
--   - Any trigger that recalculates net_profit, total_cost, or *_cost fields
--   - Any generated column on financial fields
-- All financial calculations are performed by n8n and written as plain values.
-- ============================================================
